apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      cors:
        allowCredentials: true
        allowHeaders:
        - content-type
        allowMethods:
        - POST
        allowOriginRegex:
        - '/*'
    routes:
    - graphqlApiRef:
        name: stitched-gql
        namespace: gloo-system
      matchers:
      - prefix: /graphql
      options:
        extauth:
          configRef:
            name: apikey-auth
            namespace: gloo-system
        # The following will mask the Id field from being returned to the client.
        dlp:
          actions:
          - customAction:
              maskChar: "*"
              name: test   # only used for logging
              percent:
                value: 60
              regexActions:
              - regex: '"username":[^"]*"([^"]*)"'
                subgroup: 1
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: gloo-system-gloo-fed-console-8090
            namespace: gloo-system              
  
                    

